//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcOneWeb.Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int id { get; set; }
        public string DUI { get; set; }
        public string nombres { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<decimal> salario { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public Nullable<int> id_cargo { get; set; }
        public string contrasena { get; set; }
    }
}
